---
- name: Setup Tomcat
  hosts: all
  become: true
  tasks:
    - name: install java
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: install java on ubuntu
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: download tomcat packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz
        dest: /opt

    - name: untar apache packages
      unarchive:
        src: /opt/apache-tomcat-8.5.87.tar.gz
        dest: /opt
        remote_src: yes

    - name : Add Execution Permissions on startup.sh file
      file:
        path: /opt/apache-tomcat-8.5.87/bin/startup.sh
        mode: 0777

    - name: Start Tomcat Services
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.87/bin
