---
- name: this playbook install httpd
  hosts: all
  become: true
  vars:
    port: 8083
  gather_facts: yes
  tasks:
  - name: install package
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd service

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default Apache port is {{ port }} for redhat
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: "#Listen 12.34.56.78:80"
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart apache
  
  - name: Ensure the default Apache port is {{ port }} for ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: restart apache
    service:
      name: httpd
      state: restarted

  - name: restart apache2
    service:
      name: apache2
      state: restarted
